@server=http://localhost:4004
@username=alice
@password=


### Books
# @name Books_GET
GET {{server}}/odata/v4/catalog/Books
Authorization: Basic {{username}}:{{password}}


### Books
# @name Books_POST
POST {{server}}/odata/v4/catalog/Books
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": 17687516,
  "title": "title-17687516",
  "author": {
    "ID": 7071095
  },
  "stock": 85
}


### Books
# @name Books_PATCH
PATCH {{server}}/odata/v4/catalog/Books/17687516
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": 101,
  "title": "English",
  "author": {
    "ID": 1
  },
  "stock": 812
}


### Books
# @name Books_DELETE
DELETE {{server}}/odata/v4/catalog/Books/17687516
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Authors
# @name Authors_GET
GET {{server}}/odata/v4/catalog/Authors
Authorization: Basic {{username}}:{{password}}


### Authors
# @name Authors_POST
POST {{server}}/odata/v4/catalog/Authors
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": 7071095,
  "name": "name-7071095"
}


### Authors
# @name Authors_PATCH
PATCH {{server}}/odata/v4/catalog/Authors/7071095
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": 7071095,
  "name": "name-7071095"
}


### Authors
# @name Authors_DELETE
DELETE {{server}}/odata/v4/catalog/Authors/7071095
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
