@server=http://localhost:4004
@username=alice
@password=


### Books
# @name Books_GET
GET {{server}}/odata/v4/catalog/Books
Authorization: Basic {{username}}:{{password}}


### Authors
# @name Authors_GET
GET {{server}}/odata/v4/catalog/Authors
Authorization: Basic {{username}}:{{password}}


### Authors
# @name Authors_POST
POST {{server}}/odata/v4/catalog/Authors
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": 4809363,
  "name": "name-4809363"
}


### Authors
# @name Authors_PATCH
PATCH {{server}}/odata/v4/catalog/Authors/4809363
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": 4809363,
  "name": "name-4809363"
}


### Authors
# @name Authors_DELETE
DELETE {{server}}/odata/v4/catalog/Authors/4809363
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
